### ISSUE TITLE
setup.py missing specification for dependencies?

### ISSUE THREAD

**Issue by yarikoptic** [meng-du/NSplus#2]
```shell
(git)hopa:~/deb/perspect/NSplus[master]
$> pip install -e .                                             
Obtaining file:///home/yoh/deb/perspect/NSplus
Installing collected packages: NSplus
  Running setup.py develop for NSplus
Successfully installed NSplus
pip install -e .  4.21s user 0.81s system 82% cpu 6.115 total
(dev3) 1 17892.....................................:Thu 08 Aug 2019 09:56:59 AM EDT:.
(git)hopa:~/deb/perspect/NSplus[master]
$> python ./run.py                                              
Traceback (most recent call last):
  File "./run.py", line 1, in <module>
    from nsplus import gui
  File "/home/yoh/deb/perspect/NSplus/nsplus/__init__.py", line 1, in <module>
    from .src.metaplus import MetaAnalysisPlus
  File "/home/yoh/deb/perspect/NSplus/nsplus/src/__init__.py", line 2, in <module>
    from .singleterm import analyze_expression
  File "/home/yoh/deb/perspect/NSplus/nsplus/src/singleterm.py", line 1, in <module>
    from .metaplus import MetaAnalysisPlus
  File "/home/yoh/deb/perspect/NSplus/nsplus/src/metaplus.py", line 3, in <module>
    import neurosynth as ns
ModuleNotFoundError: No module named 'neurosynth'
```

While at it, also best to refactor `run.py` into a proper "entry point" or a script to be installed (again by setup.py)

**Comment by MetaD** [comment]
@yarikoptic Thanks! Just pushed a change that should fix this

**Comment by yarikoptic** [comment]
coolio, see https://github.com/neurosynth/neurosynth/issues/91

**Comment by MetaD** [comment]
Thank you!
